// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOfXirSulKiFRNqUNI9lN8rrcmYT8FoL4',
    appId: '1:704686589752:web:070dd0f07cdd116601a3cd',
    messagingSenderId: '704686589752',
    projectId: 'phonetheftguard',
    authDomain: 'phonetheftguard.firebaseapp.com',
    storageBucket: 'phonetheftguard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbU-rSWcm9C486pHQUFebizkRaegZz6VU',
    appId: '1:704686589752:android:feb9d37a4999505901a3cd',
    messagingSenderId: '704686589752',
    projectId: 'phonetheftguard',
    storageBucket: 'phonetheftguard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ZS3xoCzBg7C85eUIlLlZyao_NnqIXxM',
    appId: '1:704686589752:ios:5e86d37d39d3fecb01a3cd',
    messagingSenderId: '704686589752',
    projectId: 'phonetheftguard',
    storageBucket: 'phonetheftguard.firebasestorage.app',
    iosBundleId: 'com.example.phonetheftguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ZS3xoCzBg7C85eUIlLlZyao_NnqIXxM',
    appId: '1:704686589752:ios:5e86d37d39d3fecb01a3cd',
    messagingSenderId: '704686589752',
    projectId: 'phonetheftguard',
    storageBucket: 'phonetheftguard.firebasestorage.app',
    iosBundleId: 'com.example.phonetheftguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOfXirSulKiFRNqUNI9lN8rrcmYT8FoL4',
    appId: '1:704686589752:web:fc383c5f2af1e0c801a3cd',
    messagingSenderId: '704686589752',
    projectId: 'phonetheftguard',
    authDomain: 'phonetheftguard.firebaseapp.com',
    storageBucket: 'phonetheftguard.firebasestorage.app',
  );
}
